{
 "title": "Loki Dashboard Automated Test",
 "description": "Test Description",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource_uid", "query": "uid-value" },
   { "name": "job", "query": "label_values(job)" },
   { "name": "search_string" },
   { "name": "log_level", "query": "label_values(log_level)" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"$job\", log_level=~\"(?i)$log_level\"} |~ \"$search_string\""
    }
   ]
  },
  {
   "title": "Error Rate (5m avg)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=\"$job\"} |~ \"ERROR\" [5m]))"
    }
   ]
  },
  {
   "title": "Total Error Logs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=\"$job\"} |= \"ERROR\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Log Volume Trend",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate({job=\"$job\", log_level=~\"(?i)$log_level\"} [5m]))"
    }
   ]
  },
  {
   "title": "Hourly Log Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "count_over_time({job=\"$job\", log_level=~\"(?i)$log_level\"} [1h])"
    }
   ]
  }
 ]
}